In [1]:
import pandas as pd

In [2]:
info = {
    "name" : ["Rutu","Harshita", "Shradha"],
    "CGPA" : [8.76, 9.0, 9.8]
}
df = pd.DataFrame(info)

print(df)

       name  CGPA
0      Rutu  8.76
1  Harshita  9.00
2   Shradha  9.80

In [3]:
df

       name  CGPA
0      Rutu  8.76
1  Harshita  9.00
2   Shradha  9.80

In [4]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1

In [5]:
s = pd.Series([23, 24, 59, 90], index=["Rutuja","Eve", "Bob", "aai"])
print(s)
print(s["Eve"])
print(s.index)

Rutuja    23
Eve       24
Bob       59
aai       90
dtype: int64
24
Index(['Rutuja', 'Eve', 'Bob', 'aai'], dtype='str')

In [6]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([1,2,3,4,5])
print(s1)
print(s2)
print(s1 + s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64

In [7]:
#dictionary 
info = {
    "Name" : ["Rutu", "Eve", "bob"],
    "Age" : [23,24,25],
    "GPA" : [9.5, 9.8, 10]
}

df = pd.DataFrame(info)
print(df, type(df))

print(df.index)
print(df.columns)

   Name  Age   GPA
0  Rutu   23   9.5
1   Eve   24   9.8
2   bob   25  10.0 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='str')

In [8]:
df = pd.DataFrame([["Rutu", 23], ["Eve",24],["bob",25]], columns=["Name","Age"])
print(df)

   Name  Age
0  Rutu   23
1   Eve   24
2   bob   25

In [9]:
import numpy as np 
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [11]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [12]:
#Methods
print(df.head()) #starting 5 rows
print(df.tail())
print(df.sample(2))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID     Name  Age Department  Salary
6   7    Grace   41         HR   82000
2   3  Charlie   28    Finance   48000

In [13]:
df.info

<bound method DataFrame.info of    ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000>

In [14]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [15]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [16]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [17]:
#openaq dataset
#openaq dataset
df = pd.read_csv("openaq.csv", delimiter=";")
df.head()
df.tail()
df.describe()

              Value
count  4.345000e+04
mean   7.663160e+02
std    3.270961e+04
min   -4.905140e+04
25%    1.600000e+00
50%    1.039900e+01
75%    3.684375e+01
max    3.198676e+06

In [18]:
#Selection data

#columns 
df["City"]
df[["City","Location"]]

#rows
df.loc[0]
df.loc[0:2] #Start idx : end idx (inclusive)

df.iloc[0:2] #end idx : end idx (exclusive)

#cells - row, column
df.loc[4, ["City","Location"]]

df.iloc[0:3, 1:5]

df.at[0, "City"]

df["City"]

0        Budapest Budatétény
1            Budapest Honvéd
2                   Budapest
3              Kazincbarcika
4             Székesfehérvár
                ...
43445                Kowloon
43446              Hong Kong
43447                    NaN
43448                    NaN
43449                    NaN
Name: City, Length: 43450, dtype: str

In [19]:
#filtering the data
df[ df["Value"] > 100]
df.query("Value > 100 ")

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
1,HU,Budapest Honvéd,Budapest Honvéd,"47.522693, 19.069867",CO,hungary-nms,µg/m³,289.0,2023-08-10T06:00:00+10:00,Hungary
4,HU,Székesfehérvár,Székesfehérvár,"47.195944, 18.400246",CO,hungary-nms,µg/m³,237.0,2023-08-09T10:00:00+10:00,Hungary
11,IE,Dublin City,IE0098A,"53.341667, -6.288889",CO,EEA Ireland,µg/m³,370.0,2023-08-10T08:00:00+10:00,Ireland
35,IN,NaN,"Sector- 16A, Faridabad - HSPCB","28.4088421, 77.3099081",PM10,caaqm,µg/m³,634.0,2018-11-09T02:30:00+10:00,India
44,IN,NaN,"Adarsh Nagar, Jaipur - RSPCB","26.902908999999998, 75.836858",PM2.5,caaqm,µg/m³,121.7,2022-10-31T12:00:00+10:00,India
...,...,...,...,...,...,...,...,...,...,...
43430,CN,NaN,西园路,"23.671400000000002, 116.6339",CO,ChinaAQIData,µg/m³,500.0,2021-01-01T02:00:00+10:00,China
43434,CN,NaN,市监测站,"30.6133, 105.68000000000002",PM10,ChinaAQIData,µg/m³,101.0,2021-01-01T02:00:00+10:00,China
43440,CL,El Bosque,El Bosque,"-33.547099645619, -70.666204101852",PM10,Chile - SINCA,µg/m³,164.0,2023-08-10T08:00:00+10:00,Chile
43445,CN,Kowloon,Mong Kok,"22.3225, 114.16833333333334",CO,Hong Kong,µg/m³,638.6,2023-08-10T10:00:00+10:00,China
43447,CN,NaN,巨轮,"37.8964, 112.5628",O3,ChinaAQIData,µg/m³,219.0,2021-08-09T21:00:00+10:00,China

In [20]:
df

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,HU,Budapest Budatétény,Budapest Budatétény,"47.40605, 19.0099",PM2.5,hungary-nms,µg/m³,7.000000,2023-08-03T22:00:00+10:00,Hungary
1,HU,Budapest Honvéd,Budapest Honvéd,"47.522693, 19.069867",CO,hungary-nms,µg/m³,289.000000,2023-08-10T06:00:00+10:00,Hungary
2,HU,Budapest,HU0045A,"47.4919433594653, 19.08778191",SO2,EEA Hungary,µg/m³,5.496181,2023-08-10T06:00:00+10:00,Hungary
3,HU,Kazincbarcika,Kazincbarcika,"48.247032999999995, 20.61445",PM10,hungary-nms,µg/m³,6.000000,2023-08-09T10:00:00+10:00,Hungary
4,HU,Székesfehérvár,Székesfehérvár,"47.195944, 18.400246",CO,hungary-nms,µg/m³,237.000000,2023-08-09T10:00:00+10:00,Hungary
...,...,...,...,...,...,...,...,...,...,...
43445,CN,Kowloon,Mong Kok,"22.3225, 114.16833333333334",CO,Hong Kong,µg/m³,638.600000,2023-08-10T10:00:00+10:00,China
43446,CN,Hong Kong,Southern,"22.247430000000005, 114.16015",PM2.5,Hong Kong,µg/m³,5.400000,2023-08-10T10:00:00+10:00,China
43447,CN,NaN,巨轮,"37.8964, 112.5628",O3,ChinaAQIData,µg/m³,219.000000,2021-08-09T21:00:00+10:00,China
43448,CN,NaN,忠庄,"27.6486, 106.89059999999999",NO2,ChinaAQIData,µg/m³,16.000000,2021-08-09T21:00:00+10:00,China
43449,CN,NaN,马山宾馆,"30.5119, 117.0331",NO2,ChinaAQIData,µg/m³,14.000000,2021-08-09T21:00:00+10:00,China

In [21]:
#cleaning data - missing values 
df = pd.read_csv("raw_data.csv")
df.isnull()
df.isna()

df.isnull().sum()
df.dropna()  #row
df.dropna(axis=1) # col drop
df.fillna(0)
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [22]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0